export const defaultTheme = {
    colorBlack: "#333333",
    colorWhite: "#ffffff",
    colorFermBackground: "#E1EDCE",
    colorStoreBackground: "#F8DDD7",
    colorFermOwner: "#88AA4D",
    colorStoreOwner: "#F75531",
    colorForButton: "#FC9B27",
    colorForButtonHover: "#FC7427",
    pagePadding: "90px",
    indent: "20px",
    fontFamily: '"Inter", "Arial", sans-serif',
    fontSizeDefault: "18px",
    footerHeight: "80px",
    pageWidth: "1280px",
    backgroundColorGray: "#f7f7f7",
    backgroundColorBlue: "#d8ecfe",
    backgroundColorActiveTab: "#88aa4d",
    paddingSideMain:"90px",
    testdefaultBorder:"1px solid rgba(0, 0, 0, 0.1)",
  };
  